#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 15 23:22:21 2023

@author: dev
"""

import Cryptograph as coder
import DatabaseManager as db
from tkinter import Tk, simpledialog, StringVar, ttk, messagebox

class PasswordManager_Read:
    pass